### ISSUE TITLE
css自定义属性

### ISSUE THREAD

**Issue by wuzhu99** [wuzhu99/learning#1]
# 介绍
自定义属性（有时候也被称作CSS变量或者级联变量）由自定义属性标记设定值，css预处理器似乎已经成为开发css的标配，CSS选择器也借鉴了预处理器的变量定义、代码块重用常用功能。本文将详细介绍CSS选择器的新用法。
# 变量
## 定义变量

> 自定义属性与预处理器中变量的区别如下：

 - 定义变量使用的前缀
 
css自定义属性遵循SCSS类似的约定并使用 --前缀的方式：
```css
:root { --red:red; }
```
SCSS 用 $ 符号来定义变量：
```css
$red: red;
```
Less 用 @ 符号来定义变量：
```css
@red: red;
```
![在这里插入图片描述](https://img-blog.csdnimg.cn/20210222175742239.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxMTYxNjA0,size_16,color_FFFFFF,t_70)

---
## var() 函数
> 自定义属性采用 var() 函数去取值
> 
 `var( <custom-property-name> [, <declaration-value> ]? )`
 
  - `custom-property-name：自定义属性名，如以 '--' 开头的自定义属性，--default-width`
  -  `declaration-value：声明值（候选值），如果自定义属性值无效时，则使用该值替换，不能指定多个候选值，如：var(--color,
   red, blue)，但可以通过嵌套函数实现，var(--color, var(--default-color, blue))
`

```css
.text { 
	/*var()函数还有一个可选参数，用来设置默认值，当变量无法取得值时，则使用默认值*/
	color: var(--red,red);
	
	--bar: 'hello';
	/*如果变量值是一个字符串，可以与其他字符串拼接。*/
	--foo: var(--bar)' world';
	
	--width: 50;
	/* 无效 */
	width: var(--width)*2px;
	/*如果变量值是一个数值，可以结合calc使用。*/
	width: calc(var(--width)*2px);
}
```
![在这里插入图片描述](https://img-blog.csdnimg.cn/20210222175827595.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxMTYxNjA0,size_16,color_FFFFFF,t_70)

---
# @apply
>与var()相比，@apply是引用样式的集合
- 语法
```css
:root{
  --overflow-ellipsis:{
    overflow:hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  };
}
.content{
  width:200px;
  @apply --overflow-ellipsis;
}
```
**@apply还没浏览器兼容 挺突然的**
![在这里插入图片描述](https://img-blog.csdnimg.cn/2021022217421381.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQxMTYxNjA0,size_16,color_FFFFFF,t_70)
# 兼容性
对于不支持 CSS 变量的浏览器，可以采用下面的写法。
```css

@supports ( (--red: 0)) {
  /* supported */
}

@supports ( not (--red: 0)) {
  /* not supported */
}
```

好了，本文到此就介绍完了，如果你有其他的补充或者觉得我有什么地方说得不对的话可以在评论区和我一起探讨。
